enum country {
    "Bahrain",
    "Saudi Arabia",
    "Australia",
    "Azerbaijan",
    "Miami",
    "Emilia Romagna",
    "Monaco",
    "Spain",
    "Canada",
    "Austria",
    "Great Britain",
    "Hungary",
    "Belgium",
    "Netherlands",
    "Italy",
    "Singapore",
    "Japan",
    "Qatar",
    "United States",
    "Mexico",
    "Brazil",
    "Las Vegas",
    "Abu Dhabi",
    "France",
    "Portugal",
    "Styria",
    "Russia",
    "Turkey",
    "70th Anniversary",
    "Tuscany",
    "Eifel",
    "Sakhir",
    "China",
    "Germany",
    "Malaysia",
    "Europe",
    "South Korea",
    "India",
    "San Marino",
    "Argentina",
    "Luxembourg",
}